export const CORE_WORDS = {
  apple:{m:'사과',ipa:'/ˈæpəl/',ko:'애플',pos:'noun'},
  love:{m:'사랑, 사랑하다',ipa:'/lʌv/',ko:'러브',pos:'noun · verb'},
  happy:{m:'행복한, 기쁜',ipa:'/ˈhæpi/',ko:'해피',pos:'adjective'},
  beautiful:{m:'아름다운, 멋진',ipa:'/ˈbjuːtəfəl/',ko:'뷰티풀',pos:'adjective'},
  dream:{m:'꿈, 꿈꾸다',ipa:'/driːm/',ko:'드림',pos:'noun · verb'},
  middle:{m:'중간, 가운데, 중앙의',ipa:'/ˈmɪdəl/',ko:'미들',pos:'noun · adjective'},
  center:{m:'중심, 중앙, 중심에 두다',ipa:'/ˈsentər/',ko:'센터',pos:'noun · verb'},
  good:{m:'좋은, 훌륭한',ipa:'/ɡʊd/',ko:'굿',pos:'adjective'},
  bad:{m:'나쁜',ipa:'/bæd/',ko:'배드',pos:'adjective'},
  big:{m:'큰',ipa:'/bɪɡ/',ko:'빅',pos:'adjective'},
  small:{m:'작은',ipa:'/smɔːl/',ko:'스몰',pos:'adjective'},
  new:{m:'새로운',ipa:'/nuː/',ko:'뉴',pos:'adjective'},
  old:{m:'오래된, 나이 든',ipa:'/oʊld/',ko:'올드',pos:'adjective'},
  fast:{m:'빠른, 빨리',ipa:'/fæst/',ko:'패스트',pos:'adjective · adverb'},
  slow:{m:'느린, 천천히',ipa:'/sloʊ/',ko:'슬로우',pos:'adjective · adverb'},
  hot:{m:'뜨거운, 더운',ipa:'/hɑːt/',ko:'핫',pos:'adjective'},
  cold:{m:'차가운, 추운',ipa:'/koʊld/',ko:'콜드',pos:'adjective'},
  easy:{m:'쉬운',ipa:'/ˈiːzi/',ko:'이지',pos:'adjective'},
  hard:{m:'어려운, 단단한',ipa:'/hɑːrd/',ko:'하드',pos:'adjective'},
  right:{m:'옳은, 오른쪽',ipa:'/raɪt/',ko:'라이트',pos:'adjective · noun'},
  left:{m:'왼쪽, 떠났다',ipa:'/left/',ko:'레프트',pos:'noun · verb'},
  up:{m:'위로, 위의',ipa:'/ʌp/',ko:'업',pos:'adverb'},
  down:{m:'아래로, 아래의',ipa:'/daʊn/',ko:'다운',pos:'adverb'},
  inside:{m:'안쪽, 내부에',ipa:'/ˌɪnˈsaɪd/',ko:'인사이드',pos:'noun · adverb'},
  outside:{m:'바깥, 밖에',ipa:'/ˌaʊtˈsaɪd/',ko:'아웃사이드',pos:'noun · adverb'},
  near:{m:'가까운, 가까이',ipa:'/nɪr/',ko:'니어',pos:'adjective · adverb'},
  far:{m:'먼, 멀리',ipa:'/fɑːr/',ko:'파',pos:'adjective · adverb'},
  first:{m:'첫째의, 처음',ipa:'/fɜːrst/',ko:'퍼스트',pos:'adjective · adverb'},
  last:{m:'마지막의, 지속되다',ipa:'/læst/',ko:'라스트',pos:'adjective · verb'},
  next:{m:'다음의, 다음에',ipa:'/nekst/',ko:'넥스트',pos:'adjective · adverb'},
  time:{m:'시간, 때',ipa:'/taɪm/',ko:'타임',pos:'noun'},
  day:{m:'날, 하루',ipa:'/deɪ/',ko:'데이',pos:'noun'},
  night:{m:'밤',ipa:'/naɪt/',ko:'나이트',pos:'noun'},
  morning:{m:'아침',ipa:'/ˈmɔːrnɪŋ/',ko:'모닝',pos:'noun'},
  today:{m:'오늘',ipa:'/təˈdeɪ/',ko:'투데이',pos:'noun · adverb'},
  tomorrow:{m:'내일',ipa:'/təˈmɑːroʊ/',ko:'투마로우',pos:'noun · adverb'},
  yesterday:{m:'어제',ipa:'/ˈjestərdeɪ/',ko:'예스터데이',pos:'noun · adverb'},
  home:{m:'집, 가정',ipa:'/hoʊm/',ko:'홈',pos:'noun'},
  house:{m:'집, 주택',ipa:'/haʊs/',ko:'하우스',pos:'noun'},
  room:{m:'방, 공간',ipa:'/ruːm/',ko:'룸',pos:'noun'},
  school:{m:'학교',ipa:'/skuːl/',ko:'스쿨',pos:'noun'},
  book:{m:'책, 예약하다',ipa:'/bʊk/',ko:'북',pos:'noun · verb'},
  study:{m:'공부하다, 연구',ipa:'/ˈstʌdi/',ko:'스터디',pos:'noun · verb'},
  learn:{m:'배우다',ipa:'/lɜːrn/',ko:'런',pos:'verb'},
  read:{m:'읽다',ipa:'/riːd/',ko:'리드',pos:'verb'},
  write:{m:'쓰다',ipa:'/raɪt/',ko:'라이트',pos:'verb'},
  speak:{m:'말하다',ipa:'/spiːk/',ko:'스피크',pos:'verb'},
  listen:{m:'듣다',ipa:'/ˈlɪsən/',ko:'리슨',pos:'verb'},
  see:{m:'보다, 알다',ipa:'/siː/',ko:'씨',pos:'verb'},
  look:{m:'보다, 바라보다',ipa:'/lʊk/',ko:'룩',pos:'verb'},
  watch:{m:'보다, 시청하다',ipa:'/wɑːtʃ/',ko:'와치',pos:'verb'},
  think:{m:'생각하다',ipa:'/θɪŋk/',ko:'씽크',pos:'verb'},
  know:{m:'알다',ipa:'/noʊ/',ko:'노우',pos:'verb'},
  understand:{m:'이해하다',ipa:'/ˌʌndərˈstænd/',ko:'언더스탠드',pos:'verb'},
  remember:{m:'기억하다',ipa:'/rɪˈmembər/',ko:'리멤버',pos:'verb'},
  forget:{m:'잊다',ipa:'/fərˈɡet/',ko:'포겟',pos:'verb'},
  go:{m:'가다',ipa:'/ɡoʊ/',ko:'고우',pos:'verb'},
  come:{m:'오다',ipa:'/kʌm/',ko:'컴',pos:'verb'},
  walk:{m:'걷다',ipa:'/wɔːk/',ko:'워크',pos:'verb'},
  run:{m:'달리다',ipa:'/rʌn/',ko:'런',pos:'verb'},
  sit:{m:'앉다',ipa:'/sɪt/',ko:'싯',pos:'verb'},
  stand:{m:'서다',ipa:'/stænd/',ko:'스탠드',pos:'verb'},
  open:{m:'열다, 열린',ipa:'/ˈoʊpən/',ko:'오픈',pos:'verb · adjective'},
  close:{m:'닫다, 가까운',ipa:'/kloʊz/',ko:'클로즈',pos:'verb'},
  make:{m:'만들다',ipa:'/meɪk/',ko:'메이크',pos:'verb'},
  do:{m:'하다',ipa:'/duː/',ko:'두',pos:'verb'},
  use:{m:'사용하다, 사용',ipa:'/juːz/',ko:'유즈',pos:'verb · noun'},
  give:{m:'주다',ipa:'/ɡɪv/',ko:'기브',pos:'verb'},
  take:{m:'가지고 가다, 취하다',ipa:'/teɪk/',ko:'테이크',pos:'verb'},
  get:{m:'얻다, 받다',ipa:'/ɡet/',ko:'겟',pos:'verb'},
  put:{m:'놓다, 두다',ipa:'/pʊt/',ko:'풋',pos:'verb'},
  bring:{m:'가져오다',ipa:'/brɪŋ/',ko:'브링',pos:'verb'},
  find:{m:'찾다, 발견하다',ipa:'/faɪnd/',ko:'파인드',pos:'verb'},
  want:{m:'원하다',ipa:'/wɑːnt/',ko:'원트',pos:'verb'},
  need:{m:'필요하다, 필요',ipa:'/niːd/',ko:'니드',pos:'verb · noun'},
  like:{m:'좋아하다, ~처럼',ipa:'/laɪk/',ko:'라이크',pos:'verb · preposition'},
  eat:{m:'먹다',ipa:'/iːt/',ko:'잇',pos:'verb'},
  drink:{m:'마시다, 음료',ipa:'/drɪŋk/',ko:'드링크',pos:'verb · noun'},
  water:{m:'물',ipa:'/ˈwɔːtər/',ko:'워터',pos:'noun'},
  food:{m:'음식',ipa:'/fuːd/',ko:'푸드',pos:'noun'},
  friend:{m:'친구',ipa:'/frend/',ko:'프렌드',pos:'noun'},
  family:{m:'가족',ipa:'/ˈfæməli/',ko:'패밀리',pos:'noun'},
  mother:{m:'어머니',ipa:'/ˈmʌðər/',ko:'마더',pos:'noun'},
  father:{m:'아버지',ipa:'/ˈfɑːðər/',ko:'파더',pos:'noun'},
  child:{m:'아이, 어린이',ipa:'/tʃaɪld/',ko:'차일드',pos:'noun'},
  man:{m:'남자, 사람',ipa:'/mæn/',ko:'맨',pos:'noun'},
  woman:{m:'여자, 여성',ipa:'/ˈwʊmən/',ko:'우먼',pos:'noun'},
  people:{m:'사람들',ipa:'/ˈpiːpəl/',ko:'피플',pos:'noun'},
  music:{m:'음악',ipa:'/ˈmjuːzɪk/',ko:'뮤직',pos:'noun'},
  song:{m:'노래',ipa:'/sɔːŋ/',ko:'송',pos:'noun'},
  smile:{m:'미소, 웃다',ipa:'/smaɪl/',ko:'스마일',pos:'noun · verb'},
  hope:{m:'희망, 바라다',ipa:'/hoʊp/',ko:'호프',pos:'noun · verb'},
  heart:{m:'마음, 심장',ipa:'/hɑːrt/',ko:'하트',pos:'noun'},
  world:{m:'세계',ipa:'/wɜːrld/',ko:'월드',pos:'noun'},
  life:{m:'삶, 생명',ipa:'/laɪf/',ko:'라이프',pos:'noun'},
  work:{m:'일, 일하다',ipa:'/wɜːrk/',ko:'워크',pos:'noun · verb'},
  money:{m:'돈',ipa:'/ˈmʌni/',ko:'머니',pos:'noun'},
  car:{m:'자동차',ipa:'/kɑːr/',ko:'카',pos:'noun'},
  bus:{m:'버스',ipa:'/bʌs/',ko:'버스',pos:'noun'},
  train:{m:'기차, 훈련하다',ipa:'/treɪn/',ko:'트레인',pos:'noun · verb'},
  city:{m:'도시',ipa:'/ˈsɪti/',ko:'시티',pos:'noun'},
  country:{m:'나라, 시골',ipa:'/ˈkʌntri/',ko:'컨트리',pos:'noun'},
  place:{m:'장소, 놓다',ipa:'/pleɪs/',ko:'플레이스',pos:'noun · verb'},
  start:{m:'시작하다, 시작',ipa:'/stɑːrt/',ko:'스타트',pos:'verb · noun'},
  stop:{m:'멈추다, 정지',ipa:'/stɑːp/',ko:'스탑',pos:'verb · noun'},
  begin:{m:'시작하다',ipa:'/bɪˈɡɪn/',ko:'비긴',pos:'verb'},
  end:{m:'끝, 끝나다',ipa:'/end/',ko:'엔드',pos:'noun · verb'},
  help:{m:'돕다, 도움',ipa:'/help/',ko:'헬프',pos:'verb · noun'},
  try:{m:'시도하다, 시도',ipa:'/traɪ/',ko:'트라이',pos:'verb · noun'},
  ask:{m:'묻다, 요청하다',ipa:'/æsk/',ko:'애스크',pos:'verb'},
  answer:{m:'대답, 대답하다',ipa:'/ˈænsər/',ko:'앤서',pos:'noun · verb'},
  question:{m:'질문',ipa:'/ˈkwestʃən/',ko:'퀘스천',pos:'noun'},
  true:{m:'사실인, 진짜의',ipa:'/truː/',ko:'트루',pos:'adjective'},
  false:{m:'거짓의, 틀린',ipa:'/fɔːls/',ko:'폴스',pos:'adjective'}
};

export const KOREAN_ALIASES = {
  사과:'apple',사랑:'love',행복:'happy',행복한:'happy',아름다운:'beautiful',아름답다:'beautiful',
  꿈:'dream',가운데:'middle',중간:'middle',중앙:'center',센터:'center',좋은:'good',좋다:'good',
  나쁜:'bad',크다:'big',큰:'big',작다:'small',작은:'small',빠르다:'fast',느리다:'slow',
  새로운:'new',오래된:'old',뜨거운:'hot',차가운:'cold',쉬운:'easy',어려운:'hard',
  오른쪽:'right',왼쪽:'left',위:'up',아래:'down',안쪽:'inside',바깥:'outside',가까운:'near',
  먼:'far',첫번째:'first',마지막:'last',다음:'next',시간:'time',하루:'day',밤:'night',아침:'morning',
  오늘:'today',내일:'tomorrow',어제:'yesterday',집:'home',주택:'house',방:'room',학교:'school',
  책:'book',공부:'study',배우다:'learn',읽다:'read',쓰다:'write',말하다:'speak',듣다:'listen',
  보다:'see',바라보다:'look',시청하다:'watch',생각하다:'think',알다:'know',이해하다:'understand',
  기억하다:'remember',잊다:'forget',가다:'go',오다:'come',걷다:'walk',달리다:'run',앉다:'sit',
  서다:'stand',열다:'open',닫다:'close',만들다:'make',하다:'do',사용하다:'use',주다:'give',
  가져가다:'take',받다:'get',놓다:'put',가져오다:'bring',찾다:'find',원하다:'want',필요하다:'need',
  좋아하다:'like',먹다:'eat',마시다:'drink',물:'water',음식:'food',친구:'friend',가족:'family',
  엄마:'mother',어머니:'mother',아빠:'father',아버지:'father',아이:'child',남자:'man',여자:'woman',
  사람들:'people',음악:'music',노래:'song',미소:'smile',웃다:'smile',희망:'hope',마음:'heart',
  세계:'world',삶:'life',일:'work',돈:'money',자동차:'car',버스:'bus',기차:'train',도시:'city',
  나라:'country',장소:'place',시작:'start',멈추다:'stop',끝:'end',돕다:'help',시도하다:'try',
  묻다:'ask',대답:'answer',질문:'question',진짜:'true',거짓:'false'
};

export function getInstantCore(input){
  const raw=(input||'').trim();
  if(!raw)return null;
  const lower=raw.toLowerCase();
  const word=CORE_WORDS[lower] ? lower : KOREAN_ALIASES[raw];
  const item=word ? CORE_WORDS[word] : null;
  if(!item)return null;
  return {
    original:raw,
    inputLanguage:/[가-힣]/.test(raw)?'ko':'en',
    word,
    phonetic:item.ipa,
    koreanPronunciation:item.ko,
    meanings:[{partOfSpeech:item.pos,definition:'',korean:item.m}],
    source:'local'
  };
}
